// Notification data — combines news alerts (from content/notifications.md)
// and dynamically-generated Collaboration Playground notifications

import rawNotif from '@/content/notifications.md';
import { extractJson } from '@/app/lib/parseContent';
import { canvases, TAG_I18N } from '@/app/data/collaboration';
import { newsItems } from '@/app/data/news';

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────
export type NotificationCategory = 'news' | 'collaboration';
export type NotificationType = 'news' | 'alert' | 'analysis' | 'transcript' | 'warning' | 'tag-match';

export interface NotificationItem {
  id: string;
  category: NotificationCategory;
  type: NotificationType;
  title: string;
  source: string;
  time: string;
  read: boolean;
  tags?: string[];
  canvasId?: string;
}

interface RawNotification {
  id: string;
  type: NotificationType;
  title: string;
  source: string;
  time: string;
  read: boolean;
}

interface NotificationsPayload {
  notifications: RawNotification[];
}

// ─────────────────────────────────────────────
// News notifications — parsed from content/notifications.md
// ─────────────────────────────────────────────
const payload = extractJson<NotificationsPayload>(rawNotif);

export const newsNotifications: NotificationItem[] = payload.notifications.map((n) => ({
  ...n,
  category: 'news' as const,
}));

// ─────────────────────────────────────────────
// Collaboration notifications — generated by matching canvas tags to news
//
// For each canvas, find which of its tags match recent news (by title or company name).
// If any match, produce one "tag-match" notification for that canvas listing the matched tags.
// ─────────────────────────────────────────────
function tagMatchesNews(tag: string): boolean {
  const en = TAG_I18N[tag] ?? tag;
  const enLower = en.toLowerCase();
  // Strip trailing 's' only for regular English plurals (not words ending in 'is', 'us', 'ss')
  const enSingular =
    enLower.endsWith('s') && !enLower.endsWith('is') && !enLower.endsWith('us') && !enLower.endsWith('ss')
      ? enLower.slice(0, -1)
      : enLower;

  return newsItems.some(
    (n) =>
      n.title.toLowerCase().includes(enLower) ||
      n.title.toLowerCase().includes(enSingular) ||
      n.tags.some((t) => t.name.toLowerCase().includes(enLower)),
  );
}

export const collaborationNotifications: NotificationItem[] = canvases.flatMap((canvas) => {
  const matchedTags = canvas.tags.filter(tagMatchesNews);
  if (matchedTags.length === 0) return [];
  return [
    {
      id: `collab-${canvas.id}`,
      category: 'collaboration' as const,
      type: 'tag-match' as const,
      title: `Canvas「${canvas.title}」的關注標籤有新相關資訊`,
      source: canvas.title,
      time: '最近',
      read: false,
      tags: matchedTags,
      canvasId: canvas.id,
    },
  ];
});

// ─────────────────────────────────────────────
// Combined
// ─────────────────────────────────────────────
export const allNotifications: NotificationItem[] = [
  ...newsNotifications,
  ...collaborationNotifications,
];
